// The device unit specs the on-device mocha runner loads, in run order.
// Plain data (no Ti) so the Node guard (test/spec/specFilesRegistration_spec.js)
// can require it and assert every entry resolves to a real `<name>_spec.js` —
// a dangling entry otherwise hangs the runner silently (see index.js).
module.exports = [
  "About",
  "Help",
  "CloseButton",
  "VideoView",
  "AnchorBar",
  "TaxonList",
  "Habitat",
  "KeyNode",
  "KeySearch",
  "LogIn",
  "MediaUtil",
  "MethodSelect",
  "Academy",
  "Menu",
  "Notes",
  "IosSurveyDatePicker",
  "Register",
  "QuestionController",
  "SampleTray",
  "SampleTaxaIcon",
  "Sample",
  "Speedbug",
  "Summary",
  "Survey",
  "TaxonDetails",
  "SiteDetails",
  "ViewUtils",
  //"LeafletMap",
  "MayflyEmergenceMap",
  "MayflyMusterSelect",
  "SampleSync",
  "SyncFeedback",
  "UploadBadge",
  "SampleEditMenu",
  "SampleHistory",
  "Gallery",
  "PhotoSelect",
  "PhotoPaths",
  "EditTaxon",
  "NavButton",
  "GoBackButton",
  "GoForwardButton",
  "LocationEntry",
  "Main",
  "Navigation",
  "View",
  "util/repository/LogRepository",
  "util/repository/TrainingRepository",
  "DiagnosticsBundle",
  "AppReset",
  //"Database"  - needs to run last, migrations are run in all database using test anyway
];
