# This is required for CocoaPods 1.x
install! 'cocoapods',
         :integrate_targets => false
 
platform :ios, '8.0'
use_frameworks!

target 'Waterbug' do
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
end