#!/bin/sh
#NODE_PATH=.:lib mocha specs/Key_spec.js specs/KeyNode_spec.js specs/KeyLoaderXml_spec.js specs/Question_spec.js specs/Taxon_spec.js
#NODE_PATH=.:lib mocha specs/BBoxCache_spec.js
#NODE_PATH=.:lib mocha specs/OrthogonalRectangulator_spec.js
#NODE_PATH=.:lib mocha specs/geometry_spec.js
NODE_PATH=.:lib mocha specs/geometry_spec.js 