name: Attach PR to Trello Card

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  attach-trello:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: rematocorp/trello-integration-action@v9.11.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          trello-api-key: ${{ secrets.TRELLO_KEY }}
          trello-auth-token: ${{ secrets.TRELLO_TOKEN }}
          trello-add-members-to-cards: false
          trello-add-labels-to-cards: false
